# Generated by Django 5.1.3 on 2024-12-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SKILLS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
