# Generated by Django 5.0.10 on 2024-12-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKILLS', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'managed': True, 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'managed': True, 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='courseenrollment',
            table='enrollments',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='module',
            table='moduls',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
