# Generated by Django 5.0.10 on 2025-01-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKILLS', '0003_alter_comment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='courseenrollment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lesson',
            table=None,
        ),
        migrations.AlterModelTable(
            name='module',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
