# Generated by Django 5.0.10 on 2025-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKILLS', '0004_alter_comment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
